### ISSUE TITLE
X11 GUI error - broken links

### ISSUE THREAD

**Issue by camilopq97** [kiwicampus/2D-Test-Track-Planner#2]
Currently I'm trying to fix the OpenCV - X11 GUI problem, the same that you mention on [running_dev_container.md](https://github.com/kiwicampus/2D-Test-Track-Planner/blob/main/planner/docs/running_dev_container.md). The error is similar in my case:
```
[graphics-3] No protocol specified
[graphics-3] Unable to init server: Could not connect: Connection refused
[graphics-3] 
[graphics-3] (planner_window:2451): Gtk-WARNING **: 16:53:13.602: cannot open display: :0
[ERROR] [graphics-3]: process has died [pid 2451, exit code 1, cmd '/workspace/planner/ros2/install/graphics/lib/graphics/graphics --ros-args'].
```
I've found some solutions in the links you provided there, but before I try those external solutions, I'll try the steps you mention there. You mention there's a `startXHost.sh` file with this url: [https://github.com/kiwicampus/2D-Test-Track-Planner/blob/main/planner/docs/planner/configs/startXHost.sh](https://github.com/kiwicampus/2D-Test-Track-Planner/blob/main/planner/docs/planner/configs/startXHost.sh), but it seems that the link is broken, and also I didn't found a bash script with that name in the project. 
I'd like to know if the `startXHost.sh` could solve the problem, or if I should try another solution. I tried with the `xhost +` command at the host several times, but it didn't worked.

PD: Also I found that the Youtube links to the video examples in [integration_engineer_project.md](https://github.com/kiwicampus/2D-Test-Track-Planner/blob/main/planner/docs/integration_engineer_project.md) are also broken. 

I Hope you could orientate me with this issue. Thanks.

**Comment by JohnBetaCode** [comment]
you are right about the link and the documentation, it'll be fixed, you've got +3%/5 extra to report this first.

remember change the local environment variable export DISPLAY=:0  in "env_vars.sh" in the folder "/workspace/planner/configs". Maybe the display on your pc has another ID.

if you are having troubles running GUI interfaces in a terminal in the Host Machine run the comand
`xhost +`

**Comment by camilopq97** [comment]
Change the DISPLAY env variable worked. Thanks

**Comment by JohnBetaCode** [comment]
Greate, I'll mark it as solved

**Comment by dadaroce** [comment]
### Here your amazing Poke Digi Mega Fantastic Badge.
![image](https://user-images.githubusercontent.com/39452483/116633696-d0608980-a91f-11eb-830f-cbbbde08cdef.png)

+3% points to ~~Gryffindor~~ **Camilo**

Nice contribution 👍🏽 you've two left continue earning `Amazing` extra points 😸.
