### ISSUE TITLE
Question about trapezoidal profile 

### ISSUE THREAD

**Issue by pepisg** [kiwicampus/2D-Test-Track-Planner#3]
Hi everyone! What exactly does "deceleration/acceleration factor" mean in the function [get_profile_route()](https://github.com/kiwicampus/2D-Test-Track-Planner/blob/b0eec0b71efb5a5a6fcf224ab25bee8f27b9626d/planner/ros2/src/path_planner/path_planner/node_planner.py#L448) for the parameter pt in the file node_planner.py?
Does it have a physical meaning or is it related to a physical quantity? like for instance the linear acceleration in pixels/s², the amount of time spent accelerating and decelerating, etc? 
Also, I found that in the [homework.md](https://github.com/pepisg/2D-Test-Track-Planner/blob/main/planner/docs/homework.md) file, in the description of the 5th python point, the file `node_planner.py` is said to be in the package `graphics`, but it's actually in the package `path_planner`. The link on `graphics` refers to the right package though. 

![Screenshot from 2021-04-29 16-54-55](https://user-images.githubusercontent.com/71234974/116617281-a8672b00-a90b-11eb-96c9-d9b33819fc46.png)

Thanks!

**Comment by JohnBetaCode** [comment]
It's used to calculate the time for the first part, the accelerated one. so the first time is a fraction of the total time, and the factor for obvious reason has to be less than 0.5, if you set it up in this value you won't have a constant speed part if it's greater than 0.6 you'll have negative values for the time in the decelerated part, you can decide if use it or not.

**Comment by pepisg** [comment]
Understood. Thanks!
