### ISSUE TITLE
Trapezoidal Speed Profile

### ISSUE THREAD

**Issue by Voldivh** [kiwicampus/2D-Test-Track-Planner#4]
Hello everyone!
I think there is an error on the input arguments for the get_profile_route function on the file node_planner.py. I'm trying to test the solution for the Python P5 and P6 but I'm getting the same error. I'll explain:

As stated on the documentation of the function, the input n (control points to discrete the trajectory) should be a data of type int. 
![image](https://user-images.githubusercontent.com/51831786/116744491-f9d0f200-a9bf-11eb-8f92-07d8d9cb0746.png)
However, the data i'm getting on the input is a float as shown on the next image:
![image](https://user-images.githubusercontent.com/51831786/116744732-516f5d80-a9c0-11eb-8bdc-ad3f3afa76bf.png)
I'm not sure if the error is mine or if there is something I'm doing wrong since I haven't modified the call of the function.
![image](https://user-images.githubusercontent.com/51831786/116745371-96938f80-a9c0-11eb-9a7c-d9a603d5f370.png)

Thanks all!

**Comment by dadaroce** [comment]
Hi Eloy!
Nice job 😄

[Check this](https://github.com/Voldivh/2D-Test-Track-Planner/blob/Python/P5/planner/ros2/src/path_planner/path_planner/node_planner.py#L96) and change float cast to int.

**Comment by dadaroce** [comment]
Let me know if everything is ok right now. @Voldivh 


### Here your amazing Poke Digi Mega Fantastic Badge.
![image](https://user-images.githubusercontent.com/39452483/116752110-a1ebb880-a9ca-11eb-8456-a0f01d693faf.png)

+3% points to **Eloy**

Nice contribution 👍🏽 you've two left continue earning `Amazing` extra points 😸.

**Comment by dadaroce** [comment]
Same issue here, change:

`self._TURN_CRTL_POINTS = float(os.getenv("TURN_CRTL_POINTS", default=30))`

By:
`self._TURN_CRTL_POINTS = int(os.getenv("TURN_CRTL_POINTS", default=30))`
