### ISSUE TITLE
Is it possible to make my repository private?

### ISSUE THREAD

**Issue by Voldivh** [kiwicampus/2D-Test-Track-Planner#5]
Hi again!

I noticed that my repository is public and I am concerned that anyone could potentially see my answers. I wonder if it is possible to change my repository to private so this issue can be prevented. 

Thanks in advance,
Eloy

**Comment by JohnBetaCode** [comment]
Yes you can, and make it visible on Monday

**Comment by Voldivh** [comment]
I'm having a little bit of trouble doing it. I basically clicked on settings -> manage access the following window appears: 
![image](https://user-images.githubusercontent.com/51831786/116787595-846e2b80-aa6a-11eb-9501-d183d2aea779.png)
I click on Manage access on the "Public Repository" section and the this window appears with the "Change visibility" bottom disabled. 
![image](https://user-images.githubusercontent.com/51831786/116787631-b4b5ca00-aa6a-11eb-89e5-beaabd016d7e.png)
 Is there a step I'm missing?

**Comment by JohnBetaCode** [comment]
you are right, You can not make private a forked repository, My advice is just add and commit the changes that you are making and push everything close to the medium night on Sunday.

**Comment by Voldivh** [comment]
Ok thanks!
