### ISSUE TITLE
wrong variable returned class

### ISSUE THREAD

**Issue by JeickH** [kiwicampus/2D-Test-Track-Planner#6]
I have an issue with script node_visual_gui.py on method crop_map(). this method Returns:
            roi_map: `cv2.math` valid windows or roi in map image
            roi_coord: `tuple` recenter input coordinate if condition is applied

on swith case part, line 245, when the condition CON_L and CON_T is met, it isn't create a tuple object for roi_coord, it is created a list object instead. To solve the list object error, I edit this part as:

elif CON_L and CON_T:
            roi_coord = copy.deepcopy(coord)
            coord[1] = win_half_height
            coord[0] = win_half_width
            # CORREGIR ERROR
            roi_coord = tuple(roi_coord)

Is this correct?

**Comment by JohnBetaCode** [comment]
you dont have to touch the function, just previously the call
