### ISSUE TITLE
speaker node callback not answering

### ISSUE THREAD

**Issue by camilopq97** [kiwicampus/2D-Test-Track-Planner#8]
I'm having an odd issue with the `speaker.cpp` node. 
I worked on all the C++ points: the `m_done_pub` is working right publishing on `"/device/speaker/done"`, also I'm playing the default track2 well.
The problem is when I'm running all the nodes together. The Python nodes (`/kiwibot_node` and `/planner_node`) publish on the `/device/speaker/command` topic. When I get the topic info via command line, I get this:

```
ros2 topic info /device/speaker/command -v
Type: std_msgs/msg/Int8

Publisher count: 2

Node name: planner_node
Node namespace: /
Topic type: std_msgs/msg/Int8
Endpoint type: PUBLISHER
GID: 01.0f.ab.0e.00.63.00.00.01.00.00.00.00.00.14.03.00.00.00.00.00.00.00.00
QoS profile:
  Reliability: RMW_QOS_POLICY_RELIABILITY_BEST_EFFORT
  Durability: RMW_QOS_POLICY_DURABILITY_VOLATILE
  Lifespan: 2147483651294967295 nanoseconds
  Deadline: 2147483651294967295 nanoseconds
  Liveliness: RMW_QOS_POLICY_LIVELINESS_AUTOMATIC
  Liveliness lease duration: 2147483651294967295 nanoseconds

Node name: kiwibot_node
Node namespace: /
Topic type: std_msgs/msg/Int8
Endpoint type: PUBLISHER
GID: 01.0f.ab.0e.fe.62.00.00.01.00.00.00.00.00.12.03.00.00.00.00.00.00.00.00
QoS profile:
  Reliability: RMW_QOS_POLICY_RELIABILITY_BEST_EFFORT
  Durability: RMW_QOS_POLICY_DURABILITY_VOLATILE
  Lifespan: 2147483651294967295 nanoseconds
  Deadline: 2147483651294967295 nanoseconds
  Liveliness: RMW_QOS_POLICY_LIVELINESS_AUTOMATIC
  Liveliness lease duration: 2147483651294967295 nanoseconds

Subscription count: 1

Node name: speaker
Node namespace: /interfaces
Topic type: std_msgs/msg/Int8
Endpoint type: SUBSCRIPTION
GID: 01.0f.ab.0e.04.63.00.00.01.00.00.00.00.00.13.04.00.00.00.00.00.00.00.00
QoS profile:
  Reliability: RMW_QOS_POLICY_RELIABILITY_RELIABLE
  Durability: RMW_QOS_POLICY_DURABILITY_VOLATILE
  Lifespan: 2147483651294967295 nanoseconds
  Deadline: 2147483651294967295 nanoseconds
  Liveliness: RMW_QOS_POLICY_LIVELINESS_AUTOMATIC
  Liveliness lease duration: 2147483651294967295 nanoseconds
```

It's clear that there are two publishers (`/kiwibot_node` and `/planner_node`) and one subscriber (`/interfaces/speaker`). 
Then I use the cmd to subscribe and inspect the topic. When I run the routine, I get the messages from the planner and kiwibot nodes, (like `data: 1`) but the speaker node DON'T DO ANYTHING. 
The weirdest thing is that, if I publish a msg on the topic with the command line, it works perfectly. Like:
```
ros2 topic pub /device/speaker/command std_msgs/msg/Int8 "data: 1" -1
publisher: beginning loop
publishing #1: std_msgs.msg.Int8(data=1)
```
When I run that, the sound is played well (including the default sound in case it isn't found). Also I get the same `data: 1` message in the subscribed cmd.
I have a `RCLCPP_INFO` printing a message inside the callback, and it only appears when the message comes from the cmd, not when it comes from the other nodes.
Here is the code where I defined the subscriber (according to the ROS2 tutorials):

```
m_speaker_sub = this->create_subscription<std_msgs::msg::Int8>(
        "/device/speaker/command", 50, default_qos, std::bind(&Speaker::speakerCb, this, _1));
```
I can't find more information about what's going on...
Hope you could guide me with that. 
Thanks.

**Comment by dadaroce** [comment]
Hi Camilo! 

First at all I don't know why your code get compiled in successful way, you're adding an extra parameter to the create_subcription function (C++ mystery)
 
Check this first:
https://docs.ros2.org/foxy/api/rclcpp/classrclcpp_1_1Node.html#a82f97ad29e3d54c91f6ef3265a8636d1

So, I guess the reason is your extra parameter.

Could you try to remove the parameter "50"? 

Something like this:

`m_speaker_sub = this->create_subscription<std_msgs::msg::Int8>(
        "/device/speaker/command", default_qos, std::bind(&Speaker::speakerCb, this, _1));`

**Comment by dadaroce** [comment]
@camilopq97 
Remember compile it again after your update 😄

**Comment by camilopq97** [comment]
You're right. Removing the 50 works :)
I was following the [Write the subscriber node](https://docs.ros.org/en/foxy/Tutorials/Writing-A-Simple-Cpp-Publisher-And-Subscriber.html#write-the-subscriber-node) tutorial. There they use a value of 10, and according to [this](https://docs.ros2.org/bouncy/api/rclcpp/classrclcpp_1_1_node.html#a2978c294db9f39677020d76d5bb14d53) documentation, it is the qos_history_depth or the "The depth of the subscription's incoming message queue." but I note that this documentation belongs to bouncy version. Maybe the foxy tutorial is outdated. That's why I was confused about it.
Anyway, thanks for your answer :)

**Comment by dadaroce** [comment]
You're changing "depth" using default_qos which provide a "proper" (sometimes this is not true) depth and configuration. So, basically your function was using 2 "QoS" profiles at the same time, resulting in a incompatibility [check it here](https://docs.ros.org/en/foxy/Concepts/About-Quality-of-Service-Settings.html#qos-compatibilities).

In another hand, the ROS2 CLI use a reader which extract the QoS used by the passed topic and setting the proper configuration according it.

@camilopq97

**Comment by camilopq97** [comment]
Okay okay I see. 
Thanks for your clarification (It's true this project is designed to learn new stuff :) )
