### ISSUE TITLE
Can't Stop the sound

### ISSUE THREAD

**Issue by Voldivh** [kiwicampus/2D-Test-Track-Planner#9]
Hello!

I think I found a bug. I was trying to stop the sound using the command explained at the documentation of the speakerCb callback.
![image](https://user-images.githubusercontent.com/51831786/116823641-33823400-ab4b-11eb-848c-4b0ad61deef8.png)
I run the project and then pub a message to that topic as is shown in the next image.
![image](https://user-images.githubusercontent.com/51831786/116823722-9ffd3300-ab4b-11eb-9ea0-4fa68ab2886b.png)
 The logic is fine since I enter the else case (where the variable m_pause should update and stop the ambient sound). However, the sound never stops.
![image](https://user-images.githubusercontent.com/51831786/116823761-03876080-ab4c-11eb-8ecd-6d7814280878.png)
I'm not sure if maybe I didn't understood the documentation. Because the update and logic makes sense. Basically the ambient sound will play as long as m_pause is 0 and m_multi_sound is 1
![image](https://user-images.githubusercontent.com/51831786/116823805-46493880-ab4c-11eb-85a4-243a2822db57.png)

Thanks.

**Comment by dadaroce** [comment]
That's the challenge 😄 and why pause the ambientSound has +15%.

Extra points doesn't have extended documentation or something like that, because you need to force your logic and capabilities to solve it. That documentation just indicate when "Pause" action should be triggered. 

> There're several ways to do it 👍🏽 

@Voldivh  Good luck!

**Comment by Voldivh** [comment]
Oh ok! So just to clarify, If i sent the 0 message the sound should stop. The thing is that I have to implement a way to make it stop. Is that right?

**Comment by dadaroce** [comment]
That's right, you could change some blocks of code if you want. Just don't broke your code and save a copy of the "homework" part to show us later.

**Comment by Voldivh** [comment]
Ok perfect! And for the homework part, I created 2 branches. The develop (with all the obligatory parts) and the feature/extra_homework. I will leave the develop branch as it is and I will keep adding the extra_points on the second branch if that's ok.

**Comment by dadaroce** [comment]
That's the way @Voldivh
